/// Represents a saved video clip of a single rally.
///
/// Clips are generated by [ClipService] after a rally completes and are stored
/// on the local filesystem. They can optionally be synced to the backend.
class Clip {
  /// Unique identifier for this clip.
  final String id;

  /// Identifier of the match this clip belongs to.
  final int matchId;

  /// Sequential rally number within the match.
  final int rallyNumber;

  /// Absolute path to the clip .mp4 file on disk.
  final String filePath;

  /// Absolute path to the thumbnail image on disk. Null if not yet generated.
  final String? thumbnailPath;

  /// Duration of the clip in seconds.
  final double durationSeconds;

  /// File size in bytes. Null if not yet measured.
  final int? fileSizeBytes;

  /// Timestamp when this clip was created.
  final DateTime createdAt;

  /// Whether this clip has been uploaded to the backend.
  final bool isUploaded;

  /// Remote URL if the clip has been uploaded. Null otherwise.
  final String? remoteUrl;

  const Clip({
    required this.id,
    required this.matchId,
    required this.rallyNumber,
    required this.filePath,
    this.thumbnailPath,
    required this.durationSeconds,
    this.fileSizeBytes,
    required this.createdAt,
    this.isUploaded = false,
    this.remoteUrl,
  });

  /// Human-readable duration string (e.g. "0:12").
  String get durationFormatted {
    final totalSeconds = durationSeconds.round();
    final minutes = totalSeconds ~/ 60;
    final seconds = totalSeconds % 60;
    return '$minutes:${seconds.toString().padLeft(2, '0')}';
  }

  /// File size in megabytes, or null if unknown.
  double? get fileSizeMB =>
      fileSizeBytes != null ? fileSizeBytes! / (1024 * 1024) : null;

  /// The clip filename derived from the naming convention.
  String get fileName => filePath.split('/').last;

  /// Creates a copy with updated fields.
  Clip copyWith({
    String? id,
    int? matchId,
    int? rallyNumber,
    String? filePath,
    String? thumbnailPath,
    double? durationSeconds,
    int? fileSizeBytes,
    DateTime? createdAt,
    bool? isUploaded,
    String? remoteUrl,
  }) {
    return Clip(
      id: id ?? this.id,
      matchId: matchId ?? this.matchId,
      rallyNumber: rallyNumber ?? this.rallyNumber,
      filePath: filePath ?? this.filePath,
      thumbnailPath: thumbnailPath ?? this.thumbnailPath,
      durationSeconds: durationSeconds ?? this.durationSeconds,
      fileSizeBytes: fileSizeBytes ?? this.fileSizeBytes,
      createdAt: createdAt ?? this.createdAt,
      isUploaded: isUploaded ?? this.isUploaded,
      remoteUrl: remoteUrl ?? this.remoteUrl,
    );
  }

  Map<String, dynamic> toJson() => {
        'id': id,
        'matchId': matchId,
        'rallyNumber': rallyNumber,
        'filePath': filePath,
        'thumbnailPath': thumbnailPath,
        'durationSeconds': durationSeconds,
        'fileSizeBytes': fileSizeBytes,
        'createdAt': createdAt.toIso8601String(),
        'isUploaded': isUploaded,
        'remoteUrl': remoteUrl,
      };

  factory Clip.fromJson(Map<String, dynamic> json) => Clip(
        id: json['id'] as String,
        matchId: json['matchId'] as int,
        rallyNumber: json['rallyNumber'] as int,
        filePath: json['filePath'] as String,
        thumbnailPath: json['thumbnailPath'] as String?,
        durationSeconds: (json['durationSeconds'] as num).toDouble(),
        fileSizeBytes: json['fileSizeBytes'] as int?,
        createdAt: DateTime.parse(json['createdAt'] as String),
        isUploaded: json['isUploaded'] as bool? ?? false,
        remoteUrl: json['remoteUrl'] as String?,
      );

  @override
  String toString() =>
      'Clip(#$rallyNumber match=$matchId ${durationFormatted}s '
      '${isUploaded ? "uploaded" : "local"})';
}
