/// A highlight bookmark with position and trim window.
///
/// The trim window ([clipStartOffset] to [clipEndOffset]) defines how much
/// video to extract around the marker position, based on user settings
/// at the time the marker was created.
class HighlightMarker {
  /// Position in the recording where the marker was placed.
  final Duration position;

  /// How many seconds before the marker to include in the clip.
  final int secondsBefore;

  /// How many seconds after the marker to include in the clip.
  final int secondsAfter;

  const HighlightMarker({
    required this.position,
    this.secondsBefore = 15,
    this.secondsAfter = 15,
  });

  /// The start of the clip to extract (clamped to 0).
  Duration get clipStart {
    final ms = position.inMilliseconds - (secondsBefore * 1000);
    return Duration(milliseconds: ms < 0 ? 0 : ms);
  }

  /// The end of the clip to extract.
  Duration get clipEnd =>
      Duration(milliseconds: position.inMilliseconds + (secondsAfter * 1000));

  /// Total duration of the highlight clip.
  int get clipDurationSeconds => secondsBefore + secondsAfter;

  /// Formatted position string (e.g. "02:34").
  String get positionFormatted {
    final totalSeconds = position.inSeconds;
    final m = totalSeconds ~/ 60;
    final s = totalSeconds % 60;
    return '${m.toString().padLeft(2, '0')}:${s.toString().padLeft(2, '0')}';
  }

  Map<String, dynamic> toJson() => {
        'positionMs': position.inMilliseconds,
        'secondsBefore': secondsBefore,
        'secondsAfter': secondsAfter,
      };

  factory HighlightMarker.fromJson(Map<String, dynamic> json) =>
      HighlightMarker(
        position: Duration(milliseconds: json['positionMs'] as int),
        secondsBefore: json['secondsBefore'] as int? ?? 15,
        secondsAfter: json['secondsAfter'] as int? ?? 15,
      );

  @override
  String toString() =>
      'Highlight(${positionFormatted}, -${secondsBefore}s/+${secondsAfter}s)';
}

/// The type of a saved clip.
enum ClipType {
  /// Clip automatically generated when a rally completes.
  rally,

  /// Clip manually triggered by the player's palm-to-racket gesture.
  highlight,
}

/// Represents a saved video clip of a single rally or highlight.
///
/// Clips are generated by [ClipService] after a rally completes or when a
/// gesture triggers a highlight save. They are stored on the local filesystem
/// and can optionally be synced to the backend.
class Clip {
  /// Unique identifier for this clip.
  final String id;

  /// Identifier of the match this clip belongs to.
  final int matchId;

  /// Sequential rally number within the match.
  final int rallyNumber;

  /// Absolute path to the clip .mp4 file on disk.
  final String filePath;

  /// Absolute path to the thumbnail image on disk. Null if not yet generated.
  final String? thumbnailPath;

  /// Duration of the clip in seconds.
  final double durationSeconds;

  /// File size in bytes. Null if not yet measured.
  final int? fileSizeBytes;

  /// Timestamp when this clip was created.
  final DateTime createdAt;

  /// The type of this clip (rally or highlight).
  final ClipType clipType;

  /// Whether this clip has been uploaded to the backend.
  final bool isUploaded;

  /// Remote URL if the clip has been uploaded. Null otherwise.
  final String? remoteUrl;

  /// Highlight bookmark markers with trim windows.
  /// Used in the player to jump to marked moments and extract clips.
  final List<HighlightMarker> highlightMarkers;

  const Clip({
    required this.id,
    required this.matchId,
    required this.rallyNumber,
    required this.filePath,
    this.thumbnailPath,
    required this.durationSeconds,
    this.fileSizeBytes,
    required this.createdAt,
    this.clipType = ClipType.rally,
    this.isUploaded = false,
    this.remoteUrl,
    this.highlightMarkers = const <HighlightMarker>[],
  });

  /// Human-readable duration string (e.g. "0:12").
  String get durationFormatted {
    final totalSeconds = durationSeconds.round();
    final minutes = totalSeconds ~/ 60;
    final seconds = totalSeconds % 60;
    return '$minutes:${seconds.toString().padLeft(2, '0')}';
  }

  /// File size in megabytes, or null if unknown.
  double? get fileSizeMB =>
      fileSizeBytes != null ? fileSizeBytes! / (1024 * 1024) : null;

  /// The clip filename derived from the naming convention.
  String get fileName => filePath.split('/').last;

  /// Whether this clip is a highlight (gesture-triggered).
  bool get isHighlight => clipType == ClipType.highlight;

  /// Whether this clip is a rally (auto-detected).
  bool get isRally => clipType == ClipType.rally;

  /// Creates a copy with updated fields.
  /// Whether this clip has highlight markers (bookmarked moments).
  bool get hasHighlights => highlightMarkers.isNotEmpty;

  /// Returns the nearest highlight marker to [position], or null if none exist.
  HighlightMarker? nearestHighlight(Duration position) {
    if (highlightMarkers.isEmpty) return null;
    HighlightMarker? nearest;
    int minDiff = 0x7FFFFFFFFFFFFFFF;
    for (final marker in highlightMarkers) {
      final diff = (marker.position.inMilliseconds - position.inMilliseconds).abs();
      if (diff < minDiff) {
        minDiff = diff;
        nearest = marker;
      }
    }
    return nearest;
  }

  /// Returns the next highlight marker after [position], or null if none.
  HighlightMarker? nextHighlight(Duration position) {
    final sorted = List<HighlightMarker>.from(highlightMarkers)
      ..sort((a, b) => a.position.compareTo(b.position));
    for (final marker in sorted) {
      if (marker.position > position) return marker;
    }
    return null;
  }

  /// Returns the previous highlight marker before [position], or null if none.
  HighlightMarker? previousHighlight(Duration position) {
    final sorted = List<HighlightMarker>.from(highlightMarkers)
      ..sort((a, b) => b.position.compareTo(a.position));
    for (final marker in sorted) {
      if (marker.position < position) return marker;
    }
    return null;
  }

  Clip copyWith({
    String? id,
    int? matchId,
    int? rallyNumber,
    String? filePath,
    String? thumbnailPath,
    double? durationSeconds,
    int? fileSizeBytes,
    DateTime? createdAt,
    ClipType? clipType,
    bool? isUploaded,
    String? remoteUrl,
    List<HighlightMarker>? highlightMarkers,
  }) {
    return Clip(
      id: id ?? this.id,
      matchId: matchId ?? this.matchId,
      rallyNumber: rallyNumber ?? this.rallyNumber,
      filePath: filePath ?? this.filePath,
      thumbnailPath: thumbnailPath ?? this.thumbnailPath,
      durationSeconds: durationSeconds ?? this.durationSeconds,
      fileSizeBytes: fileSizeBytes ?? this.fileSizeBytes,
      createdAt: createdAt ?? this.createdAt,
      clipType: clipType ?? this.clipType,
      isUploaded: isUploaded ?? this.isUploaded,
      remoteUrl: remoteUrl ?? this.remoteUrl,
      highlightMarkers: highlightMarkers ?? this.highlightMarkers,
    );
  }

  Map<String, dynamic> toJson() => {
        'id': id,
        'matchId': matchId,
        'rallyNumber': rallyNumber,
        'filePath': filePath,
        'thumbnailPath': thumbnailPath,
        'durationSeconds': durationSeconds,
        'fileSizeBytes': fileSizeBytes,
        'createdAt': createdAt.toIso8601String(),
        'clipType': clipType.name,
        'isUploaded': isUploaded,
        'remoteUrl': remoteUrl,
        'highlightMarkers': highlightMarkers.map((m) => m.toJson()).toList(),
      };

  factory Clip.fromJson(Map<String, dynamic> json) => Clip(
        id: json['id'] as String,
        matchId: json['matchId'] as int,
        rallyNumber: json['rallyNumber'] as int,
        filePath: json['filePath'] as String,
        thumbnailPath: json['thumbnailPath'] as String?,
        durationSeconds: (json['durationSeconds'] as num).toDouble(),
        fileSizeBytes: json['fileSizeBytes'] as int?,
        createdAt: DateTime.parse(json['createdAt'] as String),
        clipType: json['clipType'] != null
            ? ClipType.values.byName(json['clipType'] as String)
            : ClipType.rally,
        isUploaded: json['isUploaded'] as bool? ?? false,
        remoteUrl: json['remoteUrl'] as String?,
        highlightMarkers: (json['highlightMarkers'] as List<dynamic>?)
                ?.map((item) {
                  if (item is Map<String, dynamic>) {
                    return HighlightMarker.fromJson(item);
                  }
                  // Backwards compat: old format was just milliseconds
                  return HighlightMarker(
                    position: Duration(milliseconds: item as int),
                  );
                })
                .toList() ??
            const <HighlightMarker>[],
      );

  @override
  String toString() =>
      'Clip(${clipType.name} #$rallyNumber match=$matchId '
      '${durationFormatted}s ${isUploaded ? "uploaded" : "local"})';
}
