/// The type of a saved clip.
enum ClipType {
  /// Clip automatically generated when a rally completes.
  rally,

  /// Clip manually triggered by the player's palm-to-racket gesture.
  highlight,
}

/// Represents a saved video clip of a single rally or highlight.
///
/// Clips are generated by [ClipService] after a rally completes or when a
/// gesture triggers a highlight save. They are stored on the local filesystem
/// and can optionally be synced to the backend.
class Clip {
  /// Unique identifier for this clip.
  final String id;

  /// Identifier of the match this clip belongs to.
  final int matchId;

  /// Sequential rally number within the match.
  final int rallyNumber;

  /// Absolute path to the clip .mp4 file on disk.
  final String filePath;

  /// Absolute path to the thumbnail image on disk. Null if not yet generated.
  final String? thumbnailPath;

  /// Duration of the clip in seconds.
  final double durationSeconds;

  /// File size in bytes. Null if not yet measured.
  final int? fileSizeBytes;

  /// Timestamp when this clip was created.
  final DateTime createdAt;

  /// The type of this clip (rally or highlight).
  final ClipType clipType;

  /// Whether this clip has been uploaded to the backend.
  final bool isUploaded;

  /// Remote URL if the clip has been uploaded. Null otherwise.
  final String? remoteUrl;

  /// Highlight bookmark markers (timestamps from start of recording).
  /// Used in the player to jump to marked moments.
  final List<Duration> highlightMarkers;

  const Clip({
    required this.id,
    required this.matchId,
    required this.rallyNumber,
    required this.filePath,
    this.thumbnailPath,
    required this.durationSeconds,
    this.fileSizeBytes,
    required this.createdAt,
    this.clipType = ClipType.rally,
    this.isUploaded = false,
    this.remoteUrl,
    this.highlightMarkers = const [],
  });

  /// Human-readable duration string (e.g. "0:12").
  String get durationFormatted {
    final totalSeconds = durationSeconds.round();
    final minutes = totalSeconds ~/ 60;
    final seconds = totalSeconds % 60;
    return '$minutes:${seconds.toString().padLeft(2, '0')}';
  }

  /// File size in megabytes, or null if unknown.
  double? get fileSizeMB =>
      fileSizeBytes != null ? fileSizeBytes! / (1024 * 1024) : null;

  /// The clip filename derived from the naming convention.
  String get fileName => filePath.split('/').last;

  /// Whether this clip is a highlight (gesture-triggered).
  bool get isHighlight => clipType == ClipType.highlight;

  /// Whether this clip is a rally (auto-detected).
  bool get isRally => clipType == ClipType.rally;

  /// Creates a copy with updated fields.
  /// Whether this clip has highlight markers (bookmarked moments).
  bool get hasHighlights => highlightMarkers.isNotEmpty;

  /// Returns the nearest highlight marker to [position], or null if none exist.
  Duration? nearestHighlight(Duration position) {
    if (highlightMarkers.isEmpty) return null;
    Duration? nearest;
    int minDiff = 0x7FFFFFFFFFFFFFFF;
    for (final marker in highlightMarkers) {
      final diff = (marker.inMilliseconds - position.inMilliseconds).abs();
      if (diff < minDiff) {
        minDiff = diff;
        nearest = marker;
      }
    }
    return nearest;
  }

  /// Returns the next highlight marker after [position], or null if none.
  Duration? nextHighlight(Duration position) {
    final sorted = List<Duration>.from(highlightMarkers)
      ..sort((a, b) => a.compareTo(b));
    for (final marker in sorted) {
      if (marker > position) return marker;
    }
    return null;
  }

  /// Returns the previous highlight marker before [position], or null if none.
  Duration? previousHighlight(Duration position) {
    final sorted = List<Duration>.from(highlightMarkers)
      ..sort((a, b) => b.compareTo(a));
    for (final marker in sorted) {
      if (marker < position) return marker;
    }
    return null;
  }

  Clip copyWith({
    String? id,
    int? matchId,
    int? rallyNumber,
    String? filePath,
    String? thumbnailPath,
    double? durationSeconds,
    int? fileSizeBytes,
    DateTime? createdAt,
    ClipType? clipType,
    bool? isUploaded,
    String? remoteUrl,
    List<Duration>? highlightMarkers,
  }) {
    return Clip(
      id: id ?? this.id,
      matchId: matchId ?? this.matchId,
      rallyNumber: rallyNumber ?? this.rallyNumber,
      filePath: filePath ?? this.filePath,
      thumbnailPath: thumbnailPath ?? this.thumbnailPath,
      durationSeconds: durationSeconds ?? this.durationSeconds,
      fileSizeBytes: fileSizeBytes ?? this.fileSizeBytes,
      createdAt: createdAt ?? this.createdAt,
      clipType: clipType ?? this.clipType,
      isUploaded: isUploaded ?? this.isUploaded,
      remoteUrl: remoteUrl ?? this.remoteUrl,
      highlightMarkers: highlightMarkers ?? this.highlightMarkers,
    );
  }

  Map<String, dynamic> toJson() => {
        'id': id,
        'matchId': matchId,
        'rallyNumber': rallyNumber,
        'filePath': filePath,
        'thumbnailPath': thumbnailPath,
        'durationSeconds': durationSeconds,
        'fileSizeBytes': fileSizeBytes,
        'createdAt': createdAt.toIso8601String(),
        'clipType': clipType.name,
        'isUploaded': isUploaded,
        'remoteUrl': remoteUrl,
        'highlightMarkers': highlightMarkers.map((d) => d.inMilliseconds).toList(),
      };

  factory Clip.fromJson(Map<String, dynamic> json) => Clip(
        id: json['id'] as String,
        matchId: json['matchId'] as int,
        rallyNumber: json['rallyNumber'] as int,
        filePath: json['filePath'] as String,
        thumbnailPath: json['thumbnailPath'] as String?,
        durationSeconds: (json['durationSeconds'] as num).toDouble(),
        fileSizeBytes: json['fileSizeBytes'] as int?,
        createdAt: DateTime.parse(json['createdAt'] as String),
        clipType: json['clipType'] != null
            ? ClipType.values.byName(json['clipType'] as String)
            : ClipType.rally,
        isUploaded: json['isUploaded'] as bool? ?? false,
        remoteUrl: json['remoteUrl'] as String?,
        highlightMarkers: (json['highlightMarkers'] as List<dynamic>?)
                ?.map((ms) => Duration(milliseconds: ms as int))
                .toList() ??
            const [],
      );

  @override
  String toString() =>
      'Clip(${clipType.name} #$rallyNumber match=$matchId '
      '${durationFormatted}s ${isUploaded ? "uploaded" : "local"})';
}
